#Foreword:

#This version uses example data taken from the Freeze-Down experiment conducted in
#December 2023. This version of example code depicts a 

#Initialize all packages and tools.
#NOTE: Do NOT run these lines if packages are already installed.
#install.packages("staRdom")
#install.packages("svglite")
#install.packages("devtools") # Run this only, if devtools is not installed already.
#devtools::install_github("MatthiasPucher/staRdom")

#Initialize package library/Count CPU Cores.
#More powerful computers can use more cores to speed up processing.

library("staRdom")
library("dplyr")
library("stringr")
library("svglite")

getwd()
setwd("C:/Users/ccolo/OneDrive/Documents/GitHub/Winter-Grab-Thesis-project/1-Data/CDOM/Winter grab/WinterGrab/27Jun24")

#Read in data and visualize using an overview.
#Note that import functions are machine-specific (run help("eem_read"), and 
#file paths Will need to be changed to point at folders containing data. 
eem_list <- eem_read("C:/Users/ccolo/OneDrive/Documents/GitHub/Winter-Grab-Thesis-project/1-Data/CDOM/Winter grab/WinterGrab/27Jun24/EEMs_corrected", recursive = TRUE, import_function = 'aqualog') # in case you use your own data, just replace folder by a path. e.g. "C:/folder/another folder" and change import_function according to instrument.
View(eem_list)
eem_overview_plot(eem_list, spp=9, contour = TRUE)

#Read in absorbance. Note that absorbance and EEM files need to have 
#exactly matching names. If import continues to fail in the check data 
#step, you may need to trim absorbance columns to exclusively wavelenghth
#and absorbance columns.

absorbance_path = "C:/Users/ccolo/OneDrive/Documents/GitHub/Winter-Grab-Thesis-project/1-Data/CDOM/Winter grab/WinterGrab/27Jun24/ABS_corrected" # load example data, set a path without using system.file to use your own data e.g. "C:/folder/another folder"

absorbance <- absorbance_read(absorbance_path, recursive = TRUE, order = TRUE) # load csv or txt tables in folder

#This line of code is what makes the EEMs trimming code work. 
#It manually assigns the first column of the absorbance object as a header called "wavelength"
#It is nesseary for the eem_checkdata function
colnames(absorbance)[1] <- "wavelength"

#Read in a metadata table if present
#metatable <- system.file("extdata/metatable_dreem.csv",package = "staRdom") # path to example data, can be replaced by a path to your own data
#meta <- read.table(metatable, header = TRUE, sep = ",", dec = ".", row.names = 1) # load data
#eem_metatemplate(eem_list, absorbance) %>%
#write.csv(file="metatable.csv", row.names = FALSE)

#Check import for erorrs. This version puts the output into an object.

eem_checkdata(eem_list,absorbance)



#This line can be used to change sample names. The example code is using
#this section to remove a residual file generated by their machine. 
#eem_list <- eem_name_replace(eem_list,c("\\(FD3\\)"),c(""))

#This correction does not appear to be necessary on our aqualog if using S1c/R1c
#absorbance <- abs_blcor(absorbance,wlrange = c(680,700))

#Spectral correction. Should be corrected already if using S1c/R1c
#excorfile <- system.file("extdata/CorrectionFiles/xc06se06n.csv",package="staRdom")
#Excor <- data.table::fread(excorfile)
#emcorfile <- system.file("extdata/CorrectionFiles/mcorrs_4nm.csv",package="staRdom")
#Emcor <- data.table::fread(emcorfile)
#eem_list <- eem_range(eem_list,ex = range(Excor[,1]), em = range(Emcor[,1]))
#eem_list <- eem_spectral_cor(eem_list,Excor,Emcor)

#Subtract blanks. In this example, the machine blank must be subtracted from 
#the data. 
#eem_list <- eem_extend2largest(eem_list, interpolation = 1, extend = FALSE)
#eem_list <- eem_remove_blank(eem_list)
#eem_overview_plot(eem_list, spp=9, contour = TRUE)

#Inner filter effect correction + overview plot
eem_list <- eem_ife_correction(eem_list,absorbance, cuvl = 1)

#Raman normalization + overview plot
eem_list <- eem_raman_normalisation2(eem_list, blank = "blank")
eem_list <- eem_extract(eem_list, c("nano", "miliq", "milliq", "mq", "blank"),ignore_case = TRUE)
absorbance <- dplyr::select(absorbance, -matches("nano|miliq|milliq|mq|blank", ignore.case = TRUE))


#Remove scatter. 1st two values on the vectors are Raman scattering,
#while the second two are Rayleigh. Can be split into 4 lines
#for easier manipulation of each scattering seperately.
remove_scatter <- c(TRUE, TRUE, TRUE, TRUE)
remove_scatter_width <- c(10,10,10,10)
eem_list <- eem_rem_scat(eem_list, remove_scatter = remove_scatter, remove_scatter_width = remove_scatter_width)
eem_overview_plot(eem_list, spp=9, contour = TRUE)

#Correct for dilution. This section requires a metadata table
#in order to be used.
#eem_list <- eem_interp(eem_list, cores = cores, type = 1, extend = FALSE)
#eem_overview_plot(eem_list, spp=9, contour = TRUE)
#dil_data <- meta["dilution"]
#eem_list <- eem_dilution(eem_list,dil_data)
#eem_overview_plot(eem_list, spp=9) # plot spared, due to no dilution it looks like the previous plot.


#Data smoothing

eem4peaks <- eem_smooth(eem_list, n = 4)
summary(eem_list)

#Calculate indices (biological, fluorescence, humic) and Coble peaks
bix <- eem_biological_index(eem4peaks)
fi <- eem_fluorescence_index(eem4peaks)
hix <- eem_humification_index(eem4peaks, scale = TRUE)
coble_peaks <- eem_coble_peaks(eem4peaks)

#Joins calculations into one readout
indices_peaks <- bix %>%
  full_join(coble_peaks, by = "sample") %>%
  full_join(fi, by = "sample") %>%
  full_join(hix, by = "sample")
indices_peaks

write.csv(indices_peaks, file = "WG2_indices.csv")

#Calculates absorbance indices
slope_parms <- abs_parms(absorbance, cuvl = 1)
slope_parms
write.csv(slope_parms, file = "slope_parms.csv")








#Individual Plots. The example code below needs to be changed to the correct file path and sample ID for your setup. 

BAB23Jul241s = eem_extract(eem_list, c("BAB23Jul241s"), keep = TRUE)
ggeem(BAB23Jul241s, contour = TRUE, fill_max = 1.5)+
  ggsave('BAB23Jul241s.tiff', path ="\\\\homes.mtu.edu/home/Documents/Research/EEMS R Code/REU/Rework", dpi = 300, device = ".tiff" )

BLN23Jul241s = eem_extract(eem_list, c("BLN23Jul241s"), keep = TRUE)
ggeem(BLN23Jul241s, contour = TRUE, fill_max = 1.5)+
  ggsave('BLN23Jul241s.tiff', path ="\\\\homes.mtu.edu/home/Documents/Research/EEMS R Code/REU/Rework", dpi = 300, device = "tiff" )

FLD23Jul241s = eem_extract(eem_list, c("FLD23Jul241s"), keep = TRUE)
ggeem(FLD23Jul241s, contour = TRUE, fill_max = 1.5)+
  ggsave('FLD23Jul241s.tiff', path ="\\\\homes.mtu.edu/home/Documents/Research/EEMS R Code/REU/Rework", dpi = 300, device = "tiff" )

NEW23Jul241s = eem_extract(eem_list, c("NEW23Jul241s"), keep = TRUE)
ggeem(NEW23Jul241s, contour = TRUE, fill_max = 1.5)+
  ggsave('NEW23Jul241s.tiff', path ="\\\\homes.mtu.edu/home/Documents/Research/EEMS R Code/REU/Rework", dpi = 300, device = "tiff" )

OLD23Jul241s = eem_extract(eem_list, c("OLD23Jul241s"), keep = TRUE)
ggeem(OLD23Jul241s, contour = TRUE, fill_max = 1.5)+
  ggsave('OLD23Jul241s.tiff', path ="\\\\homes.mtu.edu/home/Documents/Research/EEMS R Code/REU/Rework", dpi = 300, device = "tiff" )


