#EEM/Parafac modeling via the staRdom package
#Reference doc at "https://cran.r-project.org/web/packages/staRdom/vignettes/PARAFAC_analysis_of_EEM.html#example-data-coming-with-the-package"

#Install Packages
install.packages('staRdom')

####################
#Temporary Code/Workspace (Delete after complation)

getwd()
setwd("\\\\homes.mtu.edu\\home\\Documents\\GitHub\\Winter-Grab-Thesis-project\\1-Data\\CDOM\\REUGreenland_V2")

####################

#Initialize libraries
library(staRdom)
library(dplyr)
library(ggplot2)
library(eemR)

#################################
#################################
#Part 1: Load and correct raw data

#Read in datafile directly from data generated by aqualog
eems <- eem_read("\\\\homes.mtu.edu\\home\\Documents\\GitHub\\Winter-Grab-Thesis-project\\1-Data\\CDOM\\REUGreenland_V2\\Trimmed EEMs", 
                 import_function = "aqualog")
eem_extend2largest(eems)
#Overview of raw reads (generates one overview per sample) 
eem_overview_plot(eems, spp=9, contour = TRUE)

#Prepare absorbance values to be read into file
#NOTE: Absorbance data file must only contain the WAVELENGTH and ABS columns.
#Extra columns will produce errors on checkdata step
absorbance_path = ("\\\\homes.mtu.edu\\home\\Documents\\GitHub\\Winter-Grab-Thesis-project\\1-Data\\CDOM\\REUGreenland_V2\\A_ABS")
absorbance = absorbance_read(absorbance_path, order = TRUE, recursive = TRUE)


#Run check on dataset. Fix errors before proceeding
eem_checkdata(eems, absorbance)

#Correct for instrumental baseline drift
absorbance = abs_blcor(absorbance, wlrange = c(680, 700))

#Spectral correction (Not present, reference doc step 5.3)

#Remove Blanks 
eems = eem_remove_blank(eems)
#Inner Filter Correction
eems = eem_ife_correction(eems, absorbance, cuvl = 5)

#Examine overview plots post-correction
eem_overview_plot(eems, spp = 9, contour = TRUE)

#Raman normalization
eems = eem_raman_normalisation2(eems, blank = "blank")

#Remove blanks
eems <- eem_extract(eems, c("nano", "miliq", "milliq", "mq", "blank"),ignore_case = TRUE)

#Remove and interpolate scattering
    #remove_scatter = c(TRUE, TRUE, TRUE, TRUE)
    #remove_scatter_width = c(15, 15, 15, 15) 

#remove and interpolate raman scattering
eems = eem_rem_scat(eems, remove_scatter = c(T,T,F,F), remove_scatter_width = c(10,5,0,0),
                    interpolation = T)

#remove rayleigh scattering
eems = eem_rem_scat(eems, remove_scatter = c(F,F,T,T) , remove_scatter_width = c(0,0,15,15),
                    interpolation = F)

#Confirm all corections have been made
summary(eems)

#View the newly created eem plots
eem_overview_plot(eems, spp = 9, contour = TRUE)

#Smooth data
eem4peaks = eem_smooth(eems, n = 4)

#Peak picking/Index creation
bix = eem_biological_index(eem4peaks)
coble_peaks = eem_coble_peaks(eem4peaks)
fi = eem_fluorescence_index(eem4peaks)
hix = eem_humification_index(eems, scale = FALSE, verbose = TRUE)

indices_peaks = bix %>%
  full_join(coble_peaks, by = "sample") %>%
  full_join(fi, by = "sample") %>%
  full_join(hix, by = "sample")

#Print a readout containing all indices
indices_peaks

#Absorbance indices
slope_parms = abs_parms(absorbance,  cuvl = 1)
slope_parms

##########################################
##########################################

#Part 2: PARAFAC Model Creation

#Extract and process sample 1 (fd3a as an example)
eems %>%
  eem_extract(sample = "BLN23Jul241s", keep = TRUE) %>%
  ggeem(eems, contour = TRUE)

eems %>%
  eem_extract(sample = "OLD23Jul241s", keep = TRUE) %>%
  ggeem(eems, contour = TRUE)

eems %>%
  eem_extract(sample = "BAB23Jul241s", keep = TRUE) %>%
  ggeem(eems, contour = TRUE)

eems %>%
  eem_extract(sample = "NEW23Jul241s", keep = TRUE) %>%
  ggeem(eems, contour = TRUE)

eems %>%
  eem_extract(sample = "FLD23Jul241s", keep = TRUE) %>%
  ggeem(eems, contour = TRUE)





