#EEM/Parafac modeling via the staRdom package
#Reference doc at "https://cran.r-project.org/web/packages/staRdom/vignettes/PARAFAC_analysis_of_EEM.html#example-data-coming-with-the-package"

#Install Packages
#install.packages('staRdom')

#Initialize libraries
library(staRdom)
library(dplyr)
library(ggplot2)
library(eemR)

#################################
#################################

#Part 1: Load and correct raw data

#Read in datafile directly from data generated by aqualog
eems <- eem_read("Trimmed EEMs", import_function = "aqualog")

#Overview of raw reads (generates one overview per sample)
eem_overview_plot(eems, spp=9, contour = TRUE)

#Prepare absorbance values to be read into file
#NOTE: Absorbance data file must only contain the WAVELENGTH and ABS columns.
#Extra columns will produce errors on checkdata step
absorbance_path = ('A_ABS')
absorbance = absorbance_read(absorbance_path, order = TRUE, recursive = TRUE)

#Run check on dataset. Fix errors before proceeding
eem_checkdata(eems, absorbance)

#Correct for instrumental baseline drift
absorbance = abs_blcor(absorbance, wlrange = c(780, 800))
#Spectral correction (Not present, reference doc step 5.3)

#Remove Blanks 
eems = eem_remove_blank(eems)

#Inner Filter Correction
eems = eem_ife_correction(eems, absorbance, cuvl = 1)

#Examine overview plots post-correction
eem_overview_plot(eems, spp = 9, contour = TRUE)

#Raman normalization
eems = eem_raman_normalisation2(eems, blank = "blank")

#Remove blanks
eems <- eem_extract(eems, c("nano", "miliq", "milliq", "mq", "blank"),ignore_case = TRUE)

#Remove and interpolate scattering
remove_scatter = c(TRUE, TRUE, FALSE, FALSE)
remove_scatter_width = c(10, 10, 0, 0)

remove_scatter = c(FALSE, FALSE, TRUE, TRUE)
remove_scatter_width = c(0, 0, 10, 10)

eems = eem_rem_scat(eems, remove_scatter = remove_scatter, remove_scatter_width = remove_scatter_width)

#Confirm all corections have been made
summary(eems)

#View the newly created eem plots
eem_overview_plot(eems, spp = 9, contour = TRUE)

#Smooth data
eem4peaks = eem_smooth(eems, n = 4)

#Peak picking/Index creation
bix = eem_biological_index(eem4peaks)
coble_peaks = eem_coble_peaks(eem4peaks)
fi = eem_fluorescence_index(eem4peaks)
hix = eem_humification_index(eem4peaks)

indices_peaks = bix %>%
  full_join(coble_peaks, by = "sample") %>%
  full_join(fi, by = "sample") %>%
  full_join(hix, by = "sample")

#Print a readout containing all indices
indices_peaks

#Absorbance indices
slope_parms = abs_parms(absorbance,  cuvl = 1)
slope_parms

##########################################
##########################################